basic:
  #app: numactl --physcpubind 0 --membind 0 dada_db -p -n 2
  app: dada_db -p -n 2
  key: aaaa
  
  writer: udp2db
  reader: #dbdisk

  bandwidth:   128    # Bandwidth in MHz of each channel
  bits:        16     # Number of bits per sample
  nchan:       1      # Number of channels
  nthread:     1      # Number of threads
  framesize:   10000  # Proposed frame size in bytes
  
# Configuration of udp2db when it is used as a writer
udp2db:
  #app: numactl --physcpubind 0 --membind 0 /data/FRIGG_2/den15c/gcorr/nic_trial/udp2db_second
  app: numactl --physcpubind 0 /data/FRIGG_2/den15c/gcorr/nic_trial/udp2db_second
  
  host:        10.17.4.1 # Host IP
  port:        10000     # port number
  
  duration:    100       # Number of seconds to run
  window:      50        # Number of MB to receive
  timeout:     10        # Number of seconds to time out

  template:    psrdada_bigcat.txt # PSRDADA header template

  reuse:       0         # SO_REUSEADD or not
  copy:        1         # Copy data to ring buffer or not
  

# Configuration of dbdisk when it is used as a reader
dbdisk:
  #app: numactl --physcpubind 0 --membind 0 dada_dbdisk -W -o -z -s
  app: dada_dbdisk -W -o -z -s
  
  directory: /data/FRIGG_2/den15c/gcorr/nic_trial # Directory to put dada file when dbdisk is used as a reader
  
